spring.datasource.url=jdbc:postgresql://localhost:5432/autonest_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.mongodb.uri=mongodb://localhost:27017/autonest_logs

server.port=8080

spring.application.name=autonest-backend

logging.level.com.autonest=DEBUG
