server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: nexabank-super-secret-key-for-jwt-signing-256-bits-long-enough

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
